### ISSUE TITLE
No module named 'pioneer.leddar_utils_cpp'

### ISSUE THREAD

**Issue by jean-lucas** [leddartech/pioneer.das.view#1]
I am trying to use the `dasview` tool to visualize one of the driving segments.

I installed it via `pip3 install pioneer-das-view`
and try to run it via: `dasview ~/projects/leddartech/data/`

But the following error appears:
```
Traceback (most recent call last):
  File "/home/jean/.local/bin/dasview", line 5, in <module>
    from pioneer.das.view.apps.dasview import main
  File "/home/jean/.local/lib/python3.8/site-packages/pioneer/das/view/__init__.py", line 5, in <module>
    from pioneer.das.view.apps import dasview
  File "/home/jean/.local/lib/python3.8/site-packages/pioneer/das/view/apps/dasview.py", line 17, in <module>
    from pioneer.das.view.viewer import Viewer
  File "/home/jean/.local/lib/python3.8/site-packages/pioneer/das/view/viewer.py", line 2, in <module>
    from pioneer.common.gui import interactive, CustomActors, utils
  File "/home/jean/.local/lib/python3.8/site-packages/pioneer/common/gui/__init__.py", line 2, in <module>
    from pioneer.leddar_utils_cpp import BVH, PointsBVH
ModuleNotFoundError: No module named 'pioneer.leddar_utils_cpp'
```

Any other packages I need to install?

**Comment by francistremblay-leddartech** [comment]
Hi,
Could you send me the result of this command please: python3.8 -m pip list | grep pioneer
Thanks

**Comment by jean-lucas** [comment]
```
pioneer-common                1.1.0
pioneer-common-gui            1.1.0
pioneer-das-api               1.1.0
pioneer-das-view              1.2.0
```

I do get the usual `pip` warning, though I assume irrelevant for this problem:
>WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.

**Comment by francistremblay-leddartech** [comment]
I see that the version 1.1.0 of pioneer.common.gui does not contain a version for python 3.8 something I fixed in the version 1.1.1. Could you try to uninstall pioneer.common.gui and reinstall pioneer.common.gui=1.1.1.

**Comment by jean-lucas** [comment]
Thanks for the quick feedback. Seems like version `1.1.1` only supports python 3.9+, not 3.8.

```
jean@lua:~$ python3.8 -m pip install pioneer.common.gui==1.1.1
Defaulting to user installation because normal site-packages is not writeable
Collecting pioneer.common.gui==1.1.1
  Using cached pioneer_common_gui-1.1.1-cp38-cp38-manylinux2014_x86_64.whl (251 kB)
Requirement already satisfied: pycollada in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (0.7.1)
Requirement already satisfied: PyQtChart==5.14 in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (5.14.0)
Requirement already satisfied: opencv-python in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (4.5.1.48)
Requirement already satisfied: utm in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (0.7.0)
Requirement already satisfied: transforms3d in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (0.3.1)
Requirement already satisfied: PyQt5==5.14 in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (5.14.0)
Requirement already satisfied: matplotlib in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (3.3.4)
Requirement already satisfied: PyOpenGL in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (3.1.5)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (1.20.1)
Requirement already satisfied: Shapely in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (1.7.1)
Requirement already satisfied: future in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (0.18.2)
Requirement already satisfied: tqdm in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (4.60.0)
Requirement already satisfied: pioneer-common in ./.local/lib/python3.8/site-packages (from pioneer.common.gui==1.1.1) (1.1.0)
ERROR: Package 'pioneer-common-gui' requires a different Python: 3.8.0 not in '>3.8.0'
```

**Comment by francistremblay-leddartech** [comment]
Hi jean-lucas, I've uploaded a new version 1.2.0, could you update your pioneer.common.gui to 1.2.0 and let me know if it works?
Thanks

**Comment by jean-lucas** [comment]
Yes this solved the problem. I can use the viewer now. 
Thanks again!

**Comment by Aditya183** [comment]
> I am trying to use the `dasview` tool to visualize one of the driving segments.
> 
> I installed it via `pip3 install pioneer-das-view`
> and try to run it via: `dasview ~/projects/leddartech/data/`
> 
> But the following error appears:
> 
> ```
> Traceback (most recent call last):
>   File "/home/jean/.local/bin/dasview", line 5, in <module>
>     from pioneer.das.view.apps.dasview import main
>   File "/home/jean/.local/lib/python3.8/site-packages/pioneer/das/view/__init__.py", line 5, in <module>
>     from pioneer.das.view.apps import dasview
>   File "/home/jean/.local/lib/python3.8/site-packages/pioneer/das/view/apps/dasview.py", line 17, in <module>
>     from pioneer.das.view.viewer import Viewer
>   File "/home/jean/.local/lib/python3.8/site-packages/pioneer/das/view/viewer.py", line 2, in <module>
>     from pioneer.common.gui import interactive, CustomActors, utils
>   File "/home/jean/.local/lib/python3.8/site-packages/pioneer/common/gui/__init__.py", line 2, in <module>
>     from pioneer.leddar_utils_cpp import BVH, PointsBVH
> ModuleNotFoundError: No module named 'pioneer.leddar_utils_cpp'
> ```
> 
> Any other packages I need to install?
Hey @jean-lucas I am doing this in google colab and as I am facing the same issue and followed the steps based on your comments above but still I am facing with Invalid syntax issue.
Can you help me out with this ??
Thanks!

**Comment by jean-lucas** [comment]
> but still I am facing with Invalid syntax issue.

~Are you facing invalid syntax, ie: `SyntaxError` or  `ModuleNotFoundError`?~

~If the former, then its probably something wrong with how your are writing your script.
If the latter, I am wondering if Google Colab is not updating pip packages correctly, maybe its caching the packages? I'm not too sure.~

~Would recommend opening up a new issue, and explaining your problem in more details there.~

EDIT:
I see you already created a new issue for this.
Seems like a different problem.

**Comment by Aditya183** [comment]
Yeah....
replying to that issue they mentioned to create a new python script to open the dasview. while running it an error is appearing: ModuleNotFoundError: No module named 'pioneer.leddar_utils_cpp'
But, while running dasview /path to dataset/ I am facing with an Invalid Syntax
![Screenshot 2021-05-20 141650](https://user-images.githubusercontent.com/55274133/119017197-5e2c1380-b9b8-11eb-9e0e-9ae7f75f3bd3.jpg)

**Comment by Aditya183** [comment]
@jean-lucas Could you please tell me the way to find out the annotation data set !?

**Comment by jean-lucas** [comment]
I would make sure all packages are installed, and at the latest versions:
```
pioneer-common          
pioneer-common-gui
pioneer-das-api
pioneer-das-view
```
If you have all the latest version and the error still shows up, maybe try switching to python3.8? I am really not sure, what else you can try. Working in the Google Colab environment can be tricky, since you don't have much control.

> Could you please tell me the way to find out the annotation data set

I am using their API for this, the `pioneer.das.api` package. From there, you can fetch labelled 3D bboxes, or get the 2D objects for the cylindrical images.

Check out the method `__update_bbox_3d` in the `pioneer.das.view` on how to project the 3D boxes to any desired camera source using their API.

**Comment by Aditya183** [comment]
> I would make sure all packages are installed, and at the latest versions:
> 
> ```
> pioneer-common          
> pioneer-common-gui
> pioneer-das-api
> pioneer-das-view
> ```
> 
> If you have all the latest version and the error still shows up, maybe try switching to python3.8? I am really not sure, what else you can try. Working in the Google Colab environment can be tricky, since you don't have much control.
> 
> > Could you please tell me the way to find out the annotation data set
> 
> I am using their API for this, the `pioneer.das.api` package. From there, you can fetch labelled 3D bboxes, or get the 2D objects for the cylindrical images.
> 
> Check out the method `__update_bbox_3d` in the `pioneer.das.view` on how to project the 3D boxes to any desired camera source using their API.

Thank you so much. I will try it once and I am getting the rawdata and pointclouds from pioneer.das.api but labelled data I am having issues.
Do pioneer.das.api or pioneer.das.view is used for the labelled data ?

**Comment by SandraVict0r** [comment]
Hello ! I have all the package with the latest version
pioneer-common          
pioneer-common-gui
pioneer-das-api
pioneer-das-view 

but when I use dasview , i still get ModuleNotFoundError: No module named 'pioneer.leddar_utils_cpp'
