### ISSUE TITLE
dasview not running

### ISSUE THREAD

**Issue by egamezl** [leddartech/pioneer.das.view#2]
Hello, 
I have been trying to make the dasview run with the suggeste command of "dasview /path/to/dataset" without success. I use the path to the set and its not working. Attached screenshot to show the issue and result. 

![image](https://user-images.githubusercontent.com/81151962/115723327-295c7a80-a380-11eb-9002-4269adad42a0.png)

This same path to the dataset I have being using for running the pioneer.das.api usage example and it worked fine. 
Can someone give me a hint on what to do? 
Thanks in advance, Esteban

**Comment by francistremblay-leddartech** [comment]
Hi,
Try putting Master AMM between quotation marks like this: "Master AMM"
