### ISSUE TITLE
dasview opening issue

### ISSUE THREAD

**Issue by Aditya183** [leddartech/pioneer.das.view#3]
Hi
I am trying to run this model in google colab. I have installed das view using 'pip install pioneer-das-view'
When I am trying to run the next step:  'dasview /path/to/dataset' I am facing syntax error issue:
![Screenshot 2021-05-20 141650](https://user-images.githubusercontent.com/55274133/118948583-0a98d600-b976-11eb-9f3f-112b7ab31050.jpg)
How to solve this?
Thanks!

**Comment by jeanlucdeziel-leddartech** [comment]
Hi,

To open the viewer, create a python script such as:

```
from pioneer.das.view.viewer import Viewer

if __name__ == "__main__":

    dataset = 'path_to_dataset'
    v = Viewer(dataset)
    v.run()
```
If you want to have a more direct way to open the viewer with a command such as dasview, you need to create an aliase that calls you python script.

**Comment by Aditya183** [comment]
> Hi,
> 
> To open the viewer, create a python script such as:
> 
> ```
> from pioneer.das.view.viewer import Viewer
> 
> if __name__ == "__main__":
> 
>     dataset = 'path_to_dataset'
>     v = Viewer(dataset)
>     v.run()
> ```
> 
> If you want to have a more direct way to open the viewer with a command such as dasview, you need to create an aliase that calls you python script.

Hey....
Thanks for reply, and we need to write it in  setup.py file !?

**Comment by jeanlucdeziel-leddartech** [comment]
> > Hi,
> > To open the viewer, create a python script such as:
> > ```
> > from pioneer.das.view.viewer import Viewer
> > 
> > if __name__ == "__main__":
> > 
> >     dataset = 'path_to_dataset'
> >     v = Viewer(dataset)
> >     v.run()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you want to have a more direct way to open the viewer with a command such as dasview, you need to create an aliase that calls you python script.
> 
> Hey....
> Thanks for reply, and we need to write it in setup.py file !?

No, in a new python file.

**Comment by Aditya183** [comment]
> > > Hi,
> > > To open the viewer, create a python script such as:
> > > ```
> > > from pioneer.das.view.viewer import Viewer
> > > 
> > > if __name__ == "__main__":
> > > 
> > >     dataset = 'path_to_dataset'
> > >     v = Viewer(dataset)
> > >     v.run()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If you want to have a more direct way to open the viewer with a command such as dasview, you need to create an aliase that calls you python script.
> > 
> > 
> > Hey....
> > Thanks for reply, and we need to write it in setup.py file !?
> 
> No, in a new python file.

Ok thank you and one last doubt,
How can collect the annotated dataset?

**Comment by Aditya183** [comment]
Hey @jeanlucdeziel-leddartech I am still facing the issues with Visualising the Annotation dataset. Is there any way to resolve it.
Thanks!

**Comment by jeanlucdeziel-leddartech** [comment]
> Hey @jeanlucdeziel-leddartech I am still facing the issues with Visualising the Annotation dataset. Is there any way to resolve it.
> Thanks!

Sorry, I missed that question. Have you downloaded annotated datasets from https://dataset.leddartech.com/ ?

**Comment by Aditya183** [comment]
> > Hey @jeanlucdeziel-leddartech I am still facing the issues with Visualising the Annotation dataset. Is there any way to resolve it.
> > Thanks!
> 
> Sorry, I missed that question. Have you downloaded annotated datasets from https://dataset.leddartech.com/ ?

Sorry, I don't see any annotated dataset in those sequences. The dataset from above link contains only raw images know!?

**Comment by jeanlucdeziel-leddartech** [comment]
All the data is there, I just tested. Here are the steps:
1. Download any dataset, for example, the first one: 20200706_171559_part27_1170_1370
2. Unzip the dataset
3. Run the script: (make sure the path to the dataset is correct)

```
from pioneer.das.view.viewer import Viewer

if __name__ == "__main__":

    dataset = '20200706_171559_part27_1170_1370'
    v = Viewer(dataset)
    v.run()
```
4. Then, a window should open. Click the "ech" box in the row identified as "pixell_bfc". You will see the surface cloud from the pixell. Then, click the tab "box3d" and check the box "pixell_bfc_box3d-deepen".

**Comment by Aditya183** [comment]
Thank you @jeanlucdeziel-leddartech I will make sure about path to the dataset and I will try it.

**Comment by Aditya183** [comment]
@jeanlucdeziel-leddartech Yeah, I have tried running the model as per your guidance and I am facing an error as:-
ModuleNotFoundError: No module named 'pioneer.leddar_utils_cpp'
For the kind information I am running it in Colab. Do I need to install any other packages!?

**Comment by jeanlucdeziel-leddartech** [comment]
The dependencies should be installing automatically. Try installing the following packages manually:
pip3 install pioneer-common
pip3 install pioneer-common-gui
pip3 install pioneer-das-api
